---
- name: update package
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    
- name: install apache2
  ansible.builtin.apt:
    name: apache2
    state: present # ultima versión
  notify: Start apache service manualmente (sin systemd)

# iniciar apache2 en un servidor
#- name: Start apache service
#  ansible.builtin.systemd_service:
#    name: apache2
#    state: started
#    enabled: true

- name: Install php depends
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-common
    - php-mysql
    - php-xml
    - php-xmlrpc
    - php-curl
    - php-gd
    - php-imagick
    - php-cli
    - php-dev
    - php-imap
    - php-mbstring
    - php-opcache
    - php-soap
    - php-zip
    - php-intl