---
- name: Wordpress
  hosts: wordpress
  become: true # instalar con sudo
  gather_facts: true # información del servidor

  tasks:
  - name: Print gather_facts
    ansible.builtin.debug:
      var: ansible_facts